# Build the manager binary
FROM registry.access.redhat.com/ubi9/go-toolset:1.25 AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /opt/app-root/src

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
COPY vendor vendor

# Copy the go source
COPY controlplane/main.go controlplane/main.go
COPY bootstrap/api/ bootstrap/api/
COPY controlplane/api/ controlplane/api/
COPY util util
COPY pkg pkg
COPY assistedinstaller assistedinstaller
COPY internal/ internal/
COPY controlplane/internal/ controlplane/internal/

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} go build -mod=vendor -a -o manager controlplane/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:8d0a8fb39ec907e8ca62cdd24b62a63ca49a30fe465798a360741fde58437a23
ARG release=main
ARG version=latest

WORKDIR /
COPY --from=builder /opt/app-root/src/manager .
USER 65532:65532

ENV SUMMARY="Cluster API Control-Plane Provider OpenShift Assisted is a CAPI control-plane provider for provisioning OpenShift clusters" \
    DESCRIPTION="Cluster API Control-Plane Provider OpenShift Assisted orchestrates cluster provisioning leveraging Assisted Installer"

LABEL name="multicluster-engine/capoa-control-plane-rhel9" \
      cpe="cpe:/a:redhat:multicluster_engine:5.0::el9" \
      summary="${SUMMARY}" \
      description="${DESCRIPTION}" \
      com.redhat.component="cluster-api-control-plane-provider-openshift-assisted" \
      io.k8s.display-name="CAPI Control-Plane Provider OpenShift Assisted" \
      io.k8s.description="${DESCRIPTION}" \
      io.openshift.tags="capi,install,cluster,provisioning,control-plane" \
      distribution-scope="public" \
      release="${release}" \
      version="${version}" \
      url="https://github.com/openshift-assisted/cluster-api-provider-openshift-assisted" \
      vendor="Red Hat, Inc."

ENTRYPOINT ["/manager"]
