//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/openshift/assisted-service/api/v1beta1"
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistrationOptions) DeepCopyInto(out *NodeRegistrationOptions) {
	*out = *in
	if in.KubeletExtraLabels != nil {
		in, out := &in.KubeletExtraLabels, &out.KubeletExtraLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistrationOptions.
func (in *NodeRegistrationOptions) DeepCopy() *NodeRegistrationOptions {
	if in == nil {
		return nil
	}
	out := new(NodeRegistrationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfig) DeepCopyInto(out *OpenshiftAssistedConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfig.
func (in *OpenshiftAssistedConfig) DeepCopy() *OpenshiftAssistedConfig {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenshiftAssistedConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfigList) DeepCopyInto(out *OpenshiftAssistedConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenshiftAssistedConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfigList.
func (in *OpenshiftAssistedConfigList) DeepCopy() *OpenshiftAssistedConfigList {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenshiftAssistedConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfigSpec) DeepCopyInto(out *OpenshiftAssistedConfigSpec) {
	*out = *in
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(v1beta1.Proxy)
		**out = **in
	}
	if in.PullSecretRef != nil {
		in, out := &in.PullSecretRef, &out.PullSecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.AdditionalNTPSources != nil {
		in, out := &in.AdditionalNTPSources, &out.AdditionalNTPSources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.NMStateConfigLabelSelector.DeepCopyInto(&out.NMStateConfigLabelSelector)
	if in.KernelArguments != nil {
		in, out := &in.KernelArguments, &out.KernelArguments
		*out = make([]v1beta1.KernelArgument, len(*in))
		copy(*out, *in)
	}
	in.NodeRegistration.DeepCopyInto(&out.NodeRegistration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfigSpec.
func (in *OpenshiftAssistedConfigSpec) DeepCopy() *OpenshiftAssistedConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfigStatus) DeepCopyInto(out *OpenshiftAssistedConfigStatus) {
	*out = *in
	if in.InfraEnvRef != nil {
		in, out := &in.InfraEnvRef, &out.InfraEnvRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.AgentRef != nil {
		in, out := &in.AgentRef, &out.AgentRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.DataSecretName != nil {
		in, out := &in.DataSecretName, &out.DataSecretName
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfigStatus.
func (in *OpenshiftAssistedConfigStatus) DeepCopy() *OpenshiftAssistedConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfigTemplate) DeepCopyInto(out *OpenshiftAssistedConfigTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfigTemplate.
func (in *OpenshiftAssistedConfigTemplate) DeepCopy() *OpenshiftAssistedConfigTemplate {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfigTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenshiftAssistedConfigTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfigTemplateList) DeepCopyInto(out *OpenshiftAssistedConfigTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenshiftAssistedConfigTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfigTemplateList.
func (in *OpenshiftAssistedConfigTemplateList) DeepCopy() *OpenshiftAssistedConfigTemplateList {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfigTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenshiftAssistedConfigTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfigTemplateResource) DeepCopyInto(out *OpenshiftAssistedConfigTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfigTemplateResource.
func (in *OpenshiftAssistedConfigTemplateResource) DeepCopy() *OpenshiftAssistedConfigTemplateResource {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfigTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfigTemplateSpec) DeepCopyInto(out *OpenshiftAssistedConfigTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfigTemplateSpec.
func (in *OpenshiftAssistedConfigTemplateSpec) DeepCopy() *OpenshiftAssistedConfigTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfigTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenshiftAssistedConfigTemplateStatus) DeepCopyInto(out *OpenshiftAssistedConfigTemplateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenshiftAssistedConfigTemplateStatus.
func (in *OpenshiftAssistedConfigTemplateStatus) DeepCopy() *OpenshiftAssistedConfigTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(OpenshiftAssistedConfigTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
