package ignition

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/coreos/ignition/v2/config/v3_1"
	config_types "github.com/coreos/ignition/v2/config/v3_1/types"
	"github.com/go-logr/logr"
	logutil "github.com/openshift-assisted/cluster-api-provider-openshift-assisted/util/log"
)

const expectedIgnitionVersion = "3.1.0"
const defaultSentinelDirectory = "/var/lib/capoa"

type ignitionVersionInfo struct {
	Ignition struct {
		Version string `json:"version"`
	} `json:"ignition"`
}

// configdriveMetadataScript reads metadata from the config-2 drive and writes
// environment variables to /etc/metadata_env in the format METADATA_<KEY>=<value>.
const configdriveMetadataScript = `#!/bin/bash

env_file=/etc/metadata_env
config_dir=$(mktemp -d)
sudo mount -L config-2 $config_dir
cat $config_dir/openstack/latest/meta_data.json | jq -r '. | keys[]' | while read key; do value=$(jq -r ".[\"$key\"]" $config_dir/openstack/latest/meta_data.json); echo "METADATA_$(echo ${key} | tr a-z A-Z | tr - _)=${value}"; done | sort | uniq | sudo tee $env_file
`

func getConfigdriveMetadataFile() config_types.File {
	return CreateIgnitionFile("/usr/local/bin/configdrive_metadata",
		"root", "data:text/plain;charset=utf-8;base64,"+base64Encode(configdriveMetadataScript), 493, true)
}

func getConfigdriveMetadataSystemdUnit() config_types.Unit {
	contents := `[Unit]
Description=Configdrive Metadata
Before=kubelet-customlabels.service
After=ostree-finalize-staged.service

[Service]
Type=oneshot

ExecStart=/usr/local/bin/configdrive_metadata
[Install]
WantedBy=multi-user.target
`
	enabled := true
	return config_types.Unit{
		Contents: &contents,
		Enabled:  &enabled,
		Name:     "configdrive-metadata.service",
	}
}

func getKubeletCustomLabelsSystemdUnit() config_types.Unit {
	contents := `[Unit]
Description=Kubelet Custom Labels
Before=kubelet.service
After=ostree-finalize-staged.service

[Service]
Type=oneshot
EnvironmentFile=/etc/metadata_env

ExecStart=/usr/local/bin/kubelet_custom_labels
[Install]
WantedBy=multi-user.target
`
	enabled := true
	return config_types.Unit{
		Contents: &contents,
		Enabled:  &enabled,
		Name:     "kubelet-customlabels.service",
	}

}

// installedNodeComponents returns the systemd units and files for the installed
// node (post-discovery) phase. These are conditionally included based on the
// IgnitionOptions:
//
// Installed node units:
//
//   - configdrive-metadata.service   — reads metadata from config-2 drive (when hostname or kubelet custom labels need it)
//   - kubelet-customlabels.service   — applies kubelet custom labels and provider ID (when KubeletCustomLabelsFile is set)
//   - set-hostname.service           — sets hostname from metadata env var (when NodeNameEnvVar is set)
//   - capoa-pre-bootstrap.service    — runs pre-bootstrap commands before kubelet (when PreBootstrapCommands is set)
//   - capoa-post-bootstrap.service   — runs post-bootstrap commands after kubelet (when PostBootstrapCommands is set)
//   - capoa-inject-provider-id.service — injects --provider-id flag into kubelet at runtime (when ProviderID is set)
//
// Discovery ignition:
//
//	Discovery-phase ignition (the boot from the discovery ISO) is configured
//	via the DiscoveryIgnitionOverrideAnnotation annotation on OpenshiftAssistedConfig.
//	No units are generated by this package for the discovery phase.
func installedNodeComponents(opts IgnitionOptions) ([]config_types.Unit, []config_types.File) {
	var units []config_types.Unit
	var files []config_types.File

	// Infrastructure: configdrive metadata is needed when hostname or kubelet
	// custom labels require resolving environment variables from the config drive.
	needsConfigdrive := opts.NodeNameEnvVar != "" || opts.KubeletCustomLabelsFile != nil
	if needsConfigdrive {
		units = append(units, getConfigdriveMetadataSystemdUnit())
		files = append(files, getConfigdriveMetadataFile())
	}

	// Kubelet custom labels and provider ID file
	if opts.KubeletCustomLabelsFile != nil {
		units = append(units, getKubeletCustomLabelsSystemdUnit())
		files = append(files, *opts.KubeletCustomLabelsFile)
	}

	// Hostname from metadata
	if opts.NodeNameEnvVar != "" {
		hostnameUnit, hostnameFile := getSetHostnameUnit(opts.NodeNameEnvVar)
		units = append(units, hostnameUnit)
		files = append(files, hostnameFile)
	}

	// Pre-bootstrap commands (before kubelet)
	if len(opts.PreBootstrapCommands) > 0 {
		unit, file := getPreBootstrapUnit(opts.PreBootstrapCommands, opts.SentinelDirectory)
		units = append(units, unit)
		files = append(files, file)
	}

	// Post-bootstrap commands (after kubelet)
	if len(opts.PostBootstrapCommands) > 0 {
		unit, file := getPostBootstrapUnit(opts.PostBootstrapCommands, opts.SentinelDirectory, opts.KubeconfigPath)
		units = append(units, unit)
		files = append(files, file)
	}

	// Kubelet provider-id injection service
	if opts.ProviderID != "" {
		providerIDUnit, providerIDFile := getProviderIDInjectorUnit()
		units = append(units, providerIDUnit)
		files = append(files, providerIDFile)
	}

	return units, files
}

// IgnitionOptions contains optional components to include in the ignition config.
type IgnitionOptions struct {
	// NodeNameEnvVar is the environment variable reference (e.g., "$METADATA_HOSTNAME")
	// to use for setting the hostname. If empty, no hostname unit is added.
	NodeNameEnvVar string

	// PreBootstrapCommands are shell commands to run before kubelet.service on first boot.
	PreBootstrapCommands []string

	// PostBootstrapCommands are shell commands to run after kubelet.service on first boot.
	PostBootstrapCommands []string

	// SentinelDirectory is the persistent directory used for run-once sentinel files.
	// If empty, /var/lib/capoa is used.
	SentinelDirectory string

	// KubeconfigPath is the kubeconfig file path for post-bootstrap readiness checks.
	// If empty, /var/lib/kubelet/kubeconfig is used.
	KubeconfigPath string

	// ProviderID is the kubelet provider ID value (e.g., "openstack://$METADATA_UUID").
	// If set, a kubelet systemd drop-in will be added to inject the --provider-id flag.
	ProviderID string

	// KubeletCustomLabelsFile is the kubelet_custom_labels script file.
	// If set, it will be added to the installed OS ignition along with its systemd unit.
	// This is needed when ProviderID or KubeletExtraLabels are configured.
	KubeletCustomLabelsFile *config_types.File
}

func sentinelDirectory(dir string) string {
	if dir == "" {
		return defaultSentinelDirectory
	}
	return strings.TrimRight(dir, "/")
}

func kubeconfigPath(path string) string {
	if path == "" {
		return "/var/lib/kubelet/kubeconfig"
	}
	return path
}

func getBootstrapCommandUnit(name, scriptPath, sentinelPath, ordering string, commands []string) (config_types.Unit, config_types.File) {
	var sb strings.Builder
	sb.WriteString("#!/bin/bash\nset -euo pipefail\n")
	for _, cmd := range commands {
		sb.WriteString(cmd)
		sb.WriteString("\n")
	}
	sentinelDir := filepath.Dir(sentinelPath)
	sb.WriteString("mkdir -p " + sentinelDir + "\ntouch " + sentinelPath + "\n")

	unitContents := `[Unit]
Description=CAPOA ` + name + `
` + ordering + `
ConditionPathExists=!` + sentinelPath + `

[Service]
Type=oneshot
ExecStart=` + scriptPath + `

[Install]
WantedBy=multi-user.target
`
	enabled := true
	unit := config_types.Unit{
		Contents: &unitContents,
		Enabled:  &enabled,
		Name:     name + ".service",
	}

	file := CreateIgnitionFile(scriptPath,
		"root", "data:text/plain;charset=utf-8;base64,"+base64Encode(sb.String()), 0700, true)

	return unit, file
}

// getPreBootstrapUnit creates a systemd oneshot unit that runs before kubelet.service.
// The After= directive lists all CAPOA units that may exist; systemd silently ignores
// ordering against absent units, so this is safe and ensures correct sequencing when
// those units are present.
func getPreBootstrapUnit(commands []string, dir string) (config_types.Unit, config_types.File) {
	sentinelPath := sentinelDirectory(dir) + "/pre-bootstrap.done"
	return getBootstrapCommandUnit(
		"capoa-pre-bootstrap",
		"/usr/local/bin/capoa-pre-bootstrap.sh",
		sentinelPath,
		"After=network.target ostree-finalize-staged.service configdrive-metadata.service kubelet-customlabels.service set-hostname.service\nBefore=kubelet.service",
		commands,
	)
}

func getPostBootstrapUnit(commands []string, dir string, kubeconfPath string) (config_types.Unit, config_types.File) {
	sentinelPath := sentinelDirectory(dir) + "/post-bootstrap.done"
	scriptPath := "/usr/local/bin/capoa-post-bootstrap.sh"
	name := "capoa-post-bootstrap"

	// Build script with kubectl API wait before user commands
	var sb strings.Builder
	sb.WriteString("#!/bin/bash\nset -euo pipefail\n\n")

	// Resolve kubeconfig path (use default if empty)
	resolvedKubeconfigPath := kubeconfigPath(kubeconfPath)

	// Wait for kube API to be accessible (max 10 minutes)
	// This polling validates both API availability and certificate validity.
	// If the kubelet client certificate is missing or invalid, kubectl commands will fail.
	fmt.Fprintf(&sb, `# Wait for kube API to be accessible (max 10 minutes)
# This polling validates both API availability and certificate validity.
# If the kubelet client certificate is missing or invalid, kubectl commands will fail.
KUBECONFIG_PATH="%s"
MAX_WAIT=600
INTERVAL=10
ELAPSED=0

echo "Waiting for kube API accessibility via ${KUBECONFIG_PATH}..."
while ! kubectl --kubeconfig="${KUBECONFIG_PATH}" get --raw /readyz >/dev/null 2>&1; do
    if [ ${ELAPSED} -ge ${MAX_WAIT} ]; then
        echo "ERROR: Timeout waiting for kube API after ${MAX_WAIT}s"
        exit 1
    fi
    echo "Still waiting for kube API to be accessible... (${ELAPSED}s elapsed)"
    sleep ${INTERVAL}
    ELAPSED=$((ELAPSED + INTERVAL))
done
echo "Kube API accessible after ${ELAPSED}s"

# Wait for node to join cluster (shares same timeout budget)
echo "Waiting for node $(hostname) to join cluster..."
while ! kubectl --kubeconfig="${KUBECONFIG_PATH}" get node "$(hostname)" >/dev/null 2>&1; do
    if [ ${ELAPSED} -ge ${MAX_WAIT} ]; then
        echo "ERROR: Timeout waiting for node $(hostname) to join cluster after ${MAX_WAIT}s"
        exit 1
    fi
    echo "Still waiting for node to be registered in cluster... (${ELAPSED}s elapsed)"
    sleep ${INTERVAL}
    ELAPSED=$((ELAPSED + INTERVAL))
done
echo "Node registered in cluster after ${ELAPSED}s"

`, resolvedKubeconfigPath)

	// Add user commands
	sb.WriteString("# Execute user-provided post-bootstrap commands\n")
	for _, cmd := range commands {
		sb.WriteString(cmd)
		sb.WriteString("\n")
	}

	// Touch sentinel
	sentinelDir := filepath.Dir(sentinelPath)
	sb.WriteString("mkdir -p " + sentinelDir + "\ntouch " + sentinelPath + "\n")

	unitContents := `[Unit]
Description=CAPOA ` + name + `
Requires=kubelet.service
After=kubelet.service
ConditionPathExists=!` + sentinelPath + `

[Service]
Type=oneshot
ExecStart=` + scriptPath + `

[Install]
WantedBy=multi-user.target
`
	enabled := true
	unit := config_types.Unit{
		Contents: &unitContents,
		Enabled:  &enabled,
		Name:     name + ".service",
	}

	file := CreateIgnitionFile(scriptPath,
		"root", "data:text/plain;charset=utf-8;base64,"+base64Encode(sb.String()), 0700, true)

	return unit, file
}

// GetIgnitionConfigOverrides builds a complete ignition config for the installed node
// (post-discovery) phase. This is used to set agent.Spec.IgnitionConfigOverrides,
// which the Assisted Installer merges into the installed OS ignition.
//
// Extra files (e.g. bootstrap-success marker) can be passed as additional arguments.
func GetIgnitionConfigOverrides(opts IgnitionOptions, extraFiles ...config_types.File) (string, error) {
	units, files := installedNodeComponents(opts)
	files = append(files, extraFiles...)

	config := config_types.Config{
		Ignition: config_types.Ignition{
			Version: "3.1.0",
		},
		Storage: config_types.Storage{
			Files: files,
		},
	}
	if len(units) > 0 {
		config.Systemd.Units = units
	}

	ignition, err := json.Marshal(config)
	if err != nil {
		return "", err
	}
	return string(ignition), nil
}

// getSetHostnameUnit creates a systemd unit and script for setting hostname from an env var.
// envVarRef can be in the form "$METADATA_NAME" or "${METADATA_NAME}".
func getSetHostnameUnit(envVarRef string) (config_types.Unit, config_types.File) {
	// Extract the variable name, handling both $VAR and ${VAR} formats
	varName := strings.TrimPrefix(envVarRef, "$")
	varName = strings.TrimPrefix(varName, "{")
	varName = strings.TrimSuffix(varName, "}")

	scriptContent := `#!/bin/bash
# Safely resolve node name from metadata environment
ENV_VAR_NAME="` + varName + `"
if [ -f /etc/metadata_env ]; then
    # Use grep to find the line, cut to extract value - no shell expansion
    NODE_NAME=$(/usr/bin/grep "^${ENV_VAR_NAME}=" /etc/metadata_env | /usr/bin/cut -d'=' -f2-)
fi
if [ -n "$NODE_NAME" ]; then
    # Use hostnamectl to set both transient and static hostname
    /usr/bin/hostnamectl set-hostname "$NODE_NAME"
fi
`

	unitContents := `[Unit]
Description=Set Hostname from Metadata
Before=kubelet.service
After=configdrive-metadata.service
Wants=configdrive-metadata.service

[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/bin/bash /usr/local/bin/set_hostname

[Install]
WantedBy=multi-user.target
`
	enabled := true
	unit := config_types.Unit{
		Contents: &unitContents,
		Enabled:  &enabled,
		Name:     "set-hostname.service",
	}

	file := CreateIgnitionFile("/usr/local/bin/set_hostname",
		"root", "data:text/plain;charset=utf-8;base64,"+base64Encode(scriptContent), 493, true)

	return unit, file
}

func base64Encode(s string) string {
	return base64.StdEncoding.EncodeToString([]byte(s))
}

// MergeIgnitionConfig merges installed-node units and files into an existing ignition
// config. This is used to add CAPOA components (hostname, kubelet labels, provider ID,
// pre/post bootstrap commands) to the ignition config from Assisted Installer for the
// installed OS (reboot phase).
func MergeIgnitionConfig(log logr.Logger, baseIgnition []byte, opts IgnitionOptions) ([]byte, error) {
	units, files := installedNodeComponents(opts)

	if len(units) == 0 && len(files) == 0 {
		return baseIgnition, nil
	}

	var versionInfo ignitionVersionInfo
	if err := json.Unmarshal(baseIgnition, &versionInfo); err == nil {
		if versionInfo.Ignition.Version != expectedIgnitionVersion {
			log.V(logutil.WarningLevel).Info(
				"base ignition config has different version than expected, fields may be silently dropped",
				"expectedVersion", expectedIgnitionVersion,
				"actualVersion", versionInfo.Ignition.Version,
			)
		}
	}

	var config config_types.Config
	if err := json.Unmarshal(baseIgnition, &config); err != nil {
		return nil, err
	}

	config.Systemd.Units = append(config.Systemd.Units, units...)
	config.Storage.Files = append(config.Storage.Files, files...)

	return json.Marshal(config)
}

func CreateIgnitionFile(path, user, content string, mode int, overwrite bool) config_types.File {
	return config_types.File{
		Node: config_types.Node{
			Path:      path,
			Overwrite: &overwrite,
			User:      config_types.NodeUser{Name: &user},
		},
		FileEmbedded1: config_types.FileEmbedded1{
			Append: []config_types.Resource{},
			Contents: config_types.Resource{
				Source: &content,
			},
			Mode: &mode,
		},
	}
}

const injectProviderIDScript = `#!/bin/bash
set -euo pipefail

PROVIDER_ID_FILE=/run/kubelet-provider-id
DROPIN_DIR=/etc/systemd/system/kubelet.service.d
DROPIN_FILE="${DROPIN_DIR}/20-provider-id.conf"
METADATA_ENV_FILE=/etc/metadata_env

PROVIDER_ID=$(cat "$PROVIDER_ID_FILE" 2>/dev/null) || true
if [ -z "$PROVIDER_ID" ]; then
    echo "inject-provider-id: no provider-id found, skipping"
    exit 0
fi

# Expand environment variables in the provider ID
# Source metadata_env if it exists to resolve variables like $METADATA_UUID
if [ -f "$METADATA_ENV_FILE" ]; then
    # Source the metadata env file to make variables available
    set -a
    source "$METADATA_ENV_FILE"
    set +a
    # Use eval to expand variables in the provider ID string
    PROVIDER_ID=$(eval echo "$PROVIDER_ID")
fi

# Extract the full ExecStart command from kubelet.service, joining
# continuation lines (backslash-newline). Filters out ExecStartPre
# and ExecStart= (clearing) lines, keeping only the actual command.
EXEC_START=$(systemctl cat kubelet.service | awk '
    /^ExecStart=/ && !/^ExecStartPre=/ && !/^ExecStart=$/ {
        sub(/^ExecStart=/, "")
        cmd = $0
        while (cmd ~ /\\$/) {
            sub(/\\$/, "", cmd)
            if (getline > 0) cmd = cmd $0
        }
        print cmd
    }
' | tail -1)

if [ -z "$EXEC_START" ]; then
    echo "inject-provider-id: WARNING: could not determine kubelet ExecStart"
    exit 1
fi

# If --provider-id is already present, skip
if echo "$EXEC_START" | grep -q -- "--provider-id"; then
    echo "inject-provider-id: --provider-id already set in kubelet ExecStart, skipping"
    exit 0
fi

# Create drop-in that overrides ExecStart with --provider-id appended
mkdir -p "$DROPIN_DIR"
cat > "$DROPIN_FILE" <<EOF
[Service]
ExecStart=
ExecStart=${EXEC_START} --provider-id="${PROVIDER_ID}"
EOF

systemctl daemon-reload
echo "inject-provider-id: injected --provider-id=${PROVIDER_ID}"
`

// getProviderIDInjectorUnit returns a systemd service and script that dynamically
// injects the --provider-id flag into kubelet.service at runtime. Unlike a static
// drop-in, this approach inspects the actual kubelet ExecStart (which is only known
// at runtime, as it is configured by the MachineConfigOperator) and:
//   - skips injection if --provider-id is already present
//   - appends --provider-id to the existing ExecStart via a generated drop-in
//   - runs daemon-reload so kubelet picks up the change before starting
func getProviderIDInjectorUnit() (config_types.Unit, config_types.File) {
	unitContents := `[Unit]
Description=Inject provider-id into kubelet
Before=kubelet.service
After=kubelet-customlabels.service
Wants=kubelet-customlabels.service

[Service]
Type=oneshot
RemainAfterExit=true
ExecStart=/usr/local/bin/inject-provider-id

[Install]
WantedBy=multi-user.target
`
	enabled := true
	unit := config_types.Unit{
		Contents: &unitContents,
		Enabled:  &enabled,
		Name:     "capoa-inject-provider-id.service",
	}

	file := CreateIgnitionFile("/usr/local/bin/inject-provider-id",
		"root", "data:text/plain;charset=utf-8;base64,"+base64Encode(injectProviderIDScript), 493, true)

	return unit, file
}

// MergeIgnitionConfigStrings merges overrideIgnition into baseIgnition.
// Both arguments must be valid Ignition config JSON (e.g. v3.1.0). The result is base plus
// override merged: the override appends or overrides fields per Ignition merge semantics.
// Returns the merged config as a JSON string. If overrideIgnition is empty, baseIgnition
// is returned unchanged.
func MergeIgnitionConfigStrings(baseIgnition, overrideIgnition string) (string, error) {
	if overrideIgnition == "" {
		return baseIgnition, nil
	}
	baseConfig, _, err := v3_1.ParseCompatibleVersion([]byte(baseIgnition))
	if err != nil {
		return "", err
	}
	overrideConfig, _, err := v3_1.ParseCompatibleVersion([]byte(overrideIgnition))
	if err != nil {
		return "", err
	}
	merged := v3_1.Merge(baseConfig, overrideConfig)
	out, err := json.Marshal(merged)
	if err != nil {
		return "", err
	}
	return string(out), nil
}
