//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	hiveextensionv1beta1 "github.com/openshift/assisted-service/api/hiveextension/v1beta1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentControlPlane) DeepCopyInto(out *AgentControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentControlPlane.
func (in *AgentControlPlane) DeepCopy() *AgentControlPlane {
	if in == nil {
		return nil
	}
	out := new(AgentControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentControlPlaneConfigSpec) DeepCopyInto(out *AgentControlPlaneConfigSpec) {
	*out = *in
	if in.PullSecretRef != nil {
		in, out := &in.PullSecretRef, &out.PullSecretRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.ClusterDeploymentRef != nil {
		in, out := &in.ClusterDeploymentRef, &out.ClusterDeploymentRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.APIVIPs != nil {
		in, out := &in.APIVIPs, &out.APIVIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IngressVIPs != nil {
		in, out := &in.IngressVIPs, &out.IngressVIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MachineNetwork != nil {
		in, out := &in.MachineNetwork, &out.MachineNetwork
		*out = make([]hiveextensionv1beta1.MachineNetworkEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentControlPlaneConfigSpec.
func (in *AgentControlPlaneConfigSpec) DeepCopy() *AgentControlPlaneConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AgentControlPlaneConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentControlPlaneList) DeepCopyInto(out *AgentControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentControlPlaneList.
func (in *AgentControlPlaneList) DeepCopy() *AgentControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(AgentControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentControlPlaneMachineTemplate) DeepCopyInto(out *AgentControlPlaneMachineTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.InfrastructureRef = in.InfrastructureRef
	if in.NodeDrainTimeout != nil {
		in, out := &in.NodeDrainTimeout, &out.NodeDrainTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NodeVolumeDetachTimeout != nil {
		in, out := &in.NodeVolumeDetachTimeout, &out.NodeVolumeDetachTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NodeDeletionTimeout != nil {
		in, out := &in.NodeDeletionTimeout, &out.NodeDeletionTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentControlPlaneMachineTemplate.
func (in *AgentControlPlaneMachineTemplate) DeepCopy() *AgentControlPlaneMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(AgentControlPlaneMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentControlPlaneSpec) DeepCopyInto(out *AgentControlPlaneSpec) {
	*out = *in
	in.AgentConfigSpec.DeepCopyInto(&out.AgentConfigSpec)
	in.MachineTemplate.DeepCopyInto(&out.MachineTemplate)
	in.AgentBootstrapConfigSpec.DeepCopyInto(&out.AgentBootstrapConfigSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentControlPlaneSpec.
func (in *AgentControlPlaneSpec) DeepCopy() *AgentControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(AgentControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentControlPlaneStatus) DeepCopyInto(out *AgentControlPlaneStatus) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(string)
		**out = **in
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(apiv1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentControlPlaneStatus.
func (in *AgentControlPlaneStatus) DeepCopy() *AgentControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(AgentControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}
