name: security-scan
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Security scan
    runs-on: ubuntu-24.04
    env:
      CONTAINER_TAG: ${{ github.sha }}
      CONTAINER_TOOL: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Jinja2 CLI
        run: pip install jinja2-cli
      - name: Build images from Dockerfile
        run: make docker-build-all
      - name: Create scans folder
        run: |
          mkdir -p scans/
      - name: Run Trivy vulnerability scanner for controlplane
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'quay.io/edge-infrastructure/cluster-api-controlplane-provider-openshift-assisted:${{ github.sha }}'
          trivy-config: .trivy.yaml
          output: 'scans/trivy-results-controlplane.sarif'
      - name: Upload Trivy scan results for controlplane to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'scans/trivy-results-controlplane.sarif'
          category: 'controlplane'
      - name: Run Trivy vulnerability scanner for bootstrap
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'quay.io/edge-infrastructure/cluster-api-bootstrap-provider-openshift-assisted:${{ github.sha }}'
          trivy-config: .trivy.yaml
          output: 'scans/trivy-results-bootstrap.sarif'
      - name: Upload Trivy scan results for bootstrap to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'scans/trivy-results-bootstrap.sarif'
          category: 'bootstrap'
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          trivy-config: .trivy.yaml
          output: 'scans/trivy-results-repo.sarif'
      - name: Upload Trivy scan results for repo to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'scans/trivy-results-repo.sarif'
          category: 'repo'
